/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 do.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/do.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model_0.geometry} material={materials['Material.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_1.geometry} material={materials['Material.003']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_2.geometry} material={materials['Material.004']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_3.geometry} material={materials['Material.005']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_4.geometry} material={materials['Material.006']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_5.geometry} material={materials['Material.007']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_6.geometry} material={materials['Material.008']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_7.geometry} material={nodes.model_7.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_8.geometry} material={materials['Material.009']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_9.geometry} material={materials['Material.010']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_10.geometry} material={materials['Material.012']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.model_11.geometry} material={materials['Material.013']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/do.glb')
